[package]
name = "glyphit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
git2 = "0.20.2"
inquire = "0.9.1"
openssl = { version = "0.10.73", features = ["vendored"] }

[dev-dependencies]
tempfile = "3"
