name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            name: Linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: Windows-x86_64
          - os: macOS-latest
            target: x86_64-apple-darwin
            name: macOS-x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Generate release notes file
        run: echo "Release notes for ${{ github.ref_name }}" > notes-${{ github.ref_name }}.md

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: glyphit
          target: ${{ matrix.platform.target }}
