name: release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux
            runs-on: ubuntu-24.04

          - os-name: Windows
            runs-on: windows-latest

          - os-name: macOS
            runs-on: macOS-latest

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: glyphit
          target: ${{ matrix.platform.target }}